Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

#Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

#Prefer single-quoted strings when you don't need string interpolation or special symbols.
StringLiterals:
  Enabled: false


#include is used at the top level. Use inside class or module.
Style/MixinUsage:
  Enabled: false


#Gems should be sorted in an alphabetical order within their section of the Gemfile. Gem listen should appear before web-console.
Bundler/OrderedGems:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
